language: java
jdk:
- oraclejdk8
script:
- mvn install -DskipITs
- mvn clean test-compile failsafe:integration-test
deploy:
  provider: heroku
  api_key: '09bbb44e-2152-4690-9d11-500e3dc909d4'
  app: elune-dev
  on:
    repo: igorstojanovski/elune
    branch: travis-build
