language: java
jdk:
- oraclejdk8
script:
- mvn install -DskipITs
- mvn clean test-compile failsafe:integration-test
deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
  app: elune-dev
  on:
    repo: igorstojanovski/elune
    branch: travis-build
